name: "test"

on:
  push:
    branches: ["main"]
    paths:
      - "**/*.js"
      - "**/*.ts"
  pull_request:
    branches: ["*"]
    paths:
      - "**/*.js"
      - "**/*.ts"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pixijs-package:
          - pixi.js@v6.1.0
          - pixi.js@v7.2.0
          - pixi.js@v8.1.0

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - run: npm install
      - name: Use ${{ matrix.pixijs-package }}
        run: npm install ${{ matrix.pixijs-package }}
      - run: npm run test
